<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
echo $this->getDesignStyles();
$package = Mage::getDesign()->getPackageName();
$theme = Mage::getDesign()->getTheme('frontend');
?>
<?php 
$totals = Mage::getSingleton('checkout/session')->getQuote()->getTotals();
$subtotal = $totals["subtotal"]->getValue();
$grandtotal = $totals["grand_total"]->getValue();
$cartItems = Mage::getModel('checkout/cart')->getQuote();
if(isset($totals['tax']) && $totals['tax']->getValue()) {
    $tax = $totals['tax']->getValue();
} else {
    $tax = '0';
}
?>
<div class="opc-wrapper-opc design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
    <div class="page-title checkout-title">
        <h1><?php echo $this->__('Checkout')?></h1>
    </div>
    <div class="row">
    <div class="col-lg-9 col-xs-12 col-sm-9">
	<div class="opc-menu">	
	    <?php echo $this->getChildHtml('paypal.button')?>	            
        <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
    		<?php echo $this->getChildHtml('login');?>	
    	<?php endif;?> 	
    	
    	<div class="right review-menu-block">
    	  <a class="review-total theme-bg-color"><i class="icon-cart"></i><?php echo Mage::helper('opc')->getGrandTotal()?></a>
    	  <div class="hidden theme-border-color" id="opc-review-block">
		      <?php echo $this->_getReviewHtml()?>
		  </div>
		</div>
	   <div class="clear move-columns"></div>
	</div>
	
	<div class="clear"></div>

    <div class="opc-col-left">
        <div class="block-title"><?php echo $this->__('1. SHIPPING')?></div>

        <form id="opc-address-form-shipping" method="post">
        	<?php echo $this->getChildHtml('shipping')?>
        </form>
		
    </div>

    <div class="opc-col-center" style="display: block !important;">
       <?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
    	<div class="shipping-block">
        	<div class="block-title"><?php echo $this->__('Shipping Method')?></div>
        	<div id="shipping-block-methods">
				<?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
			</div>
		</div>
		<?php endif;?>
		
		<?php if(Mage::helper('opc')->isShowDiscount()):?>
		<div class="discount-block">
			<h3><?php echo $this->__('Discount Codes')?><span class='expand_plus theme-bg-color'></span></h3>
			<div  class="collapse-block hidden">
			     <?php echo $this->getChildhtml('coupon');?>
			</div>
		</div>
		<?php endif;?>

		<?php if(Mage::helper('opc')->isShowComment()):?>
			<?php echo $this->getChildhtml('customer.comment');?>
		<?php endif;?>
    </div>

    <div class="opc-col-right">
                <div class="block-title"><?php echo $this->__('2. BILLING')?></div>

		<form id="opc-address-form-billing" method="post">
			<?php echo $this->getChildHtml('billing')?>
		</form>
		<div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>">
			<h3><?php echo $this->__('Payment Method')?></h3>
			<?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
		</div>
    
        <?php if (Mage::getConfig()->getModuleConfig('IWD_OnepageCheckoutSignature')->is('active', 'true')): ?>
            <div class="signature-block">
                <h3><?php echo $this->__('Signature')?><span class='expand_plus theme-bg-color'></span></h3>
                <div  class="collapse-block hidden">
                    <?php echo $this->getChildhtml('opcsignature');?>
                </div>
            </div>
        <?php endif;?>

		<div class="opc-review-actions" id="checkout-review-submit">
		      <h5 class="grand_total"><?php echo $this->__('Grand Total')?><?php echo Mage::helper('opc')->getGrandTotal()?></h5>
		      <?php echo $this->getChildHtml('agreements')?>
		      <?php echo $this->getChildHtml('opc.newsletters');?>
		      <button type="button" title="<?php echo $this->__('Place Order Now') ?>" class="button btn-checkout opc-btn-checkout"><span class="btn-img"><span><?php echo $this->__('Place Order Now') ?></span></span></button>
		</div>
    </div>
    </div>
    <div class="col-lg-3 col-xs-12 col-sm-3">
	<div class="coRight">
    <h4 class="coSummary">Order Summary <span class="coEditOrder"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'checkout/cart'; ?>">Edit Order</a></span></h4>
	<?php foreach ($cartItems->getAllItems() as $cartItem) { 
		    $cartProduct = Mage::getModel('catalog/product')->load($cartItem->getProductId());
	?> 
		<div class="coSummBlock ng-scope">
		<img alt="<?php echo $cartItem->getProduct()->getName(); ?>" class="coSummImg" src="<?php echo Mage::helper('catalog/image')->init($cartProduct, 'thumbnail')->resize(120); ?>">
		<div class="coSummName ng-binding"><?php echo $cartItem->getProduct()->getName(); ?></div>
		<div class="coSummPrice">
			<div class="coPriceText">Price:</div>
			<div class="coPriceAmt ng-binding"><?php echo Mage::helper('core')->currency($cartProduct->getFinalPrice(), true, false); ?></div>
		</div>
		<div class="coSummQty">
			<div class="coQtyText">Qty:</div>
			<div class="coQtyAmt ng-binding"><?php echo $cartItem->getQty()*1; ?></div>
		</div>
		<div class="coProdMsg ng-binding instock">
			This item is in stock.
		</div>
	</div>
		<?php } ?>
		<div class="coSubtotalBlock orderreviewblock">
		<div class="coSubtotal ng-scope">
			<div class="coTotalLeft ng-binding">Order Subtotal:</div>
			<div class="coTotalRight ng-binding"><?php echo Mage::helper('core')->currency($subtotal, true, false); ?></div>
		</div>
		<div class="coDiscount isRed ng-scope">
			<div class="coTotalLeft ng-binding">Order Discount:</div>
			<div class="coTotalRight ng-binding">**</div>
		</div>
		<div class="coShipTotal ng-scope">
			<div class="coTotalLeft">
				<span class="ng-binding">Shipping</span>
				<span class="coShipTotalMeth ng-binding ng-scope">(Economy)</span>
				<span>:</span>
			</div>

			<div class="coTotalRight ng-binding"><?php echo Mage::helper('core')->currency(Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getShippingAmount(), true, false); ?></div>
		</div>
		<div class="coTax ng-scope">
			<div class="coTotalLeft ng-binding">Sales Tax:</div>
			<div class="coTotalRight ng-binding"><?php echo Mage::helper('core')->currency($tax, true, false); ?></div>
		<div class="coOrderTotal">
			<div class="coTotalLeft ng-binding">Order Total:</div>
			<div class="coTotalRight ng-binding"><?php echo Mage::helper('core')->currency($grandtotal, true, false); ?></div>
		</div>
	</div>
    </div>
		</div>
    </div>
</div>
<script>
	var vopc = '<?php echo Mage::getConfig()->getModuleConfig("IWD_Opc")->version;?>';
	IWD.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	IWD.OPC.Checkout.isVirtual = true;
	<?php endif;?>	 
</script>

<div id="agree_error" style="display:none !important;"><?php echo $this->__('Please agree to all the terms and conditions before placing the order.');?></div>
<div id="pssm_msg" style="display:none !important;"><?php echo $this->__('Please specify shipping method');?></div>
<div class="opc-ajax-loader">
    <div style="width:100%;text-align:center;position:absolute;left:0;top:50%;font-size:16px;z-index:10;margin-top:-8px;">
	    <i class="ajax-loader large animate-spin"></i>
    </div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	
	<div class="opc-messages">
		<a class="close-message-wrapper"></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>

	<script>
		jQuery("#billing-new-address-form .input-text.required-entry, #shipping-new-address-form .input-text.required-entry").blur(function(){
			if (jQuery(this).val().length==0){
				jQuery(this).addClass('validation-failed');
				jQuery(this).removeClass('validation-passed');
				jQuery(this).parent().find('.validation-advice').remove();
				jQuery(this).after("<div class='validation-advice'>This is a required field.</div>");
			}else{
				if (jQuery(this).hasClass('validate-email')){
					if (validateEmail(jQuery(this).val())){
						jQuery(this).removeClass('validation-failed');
						jQuery(this).addClass('validation-passed');
						jQuery(this).parent().find('.validation-advice').remove();
					}else{
						jQuery(this).addClass('validation-failed');
						jQuery(this).removeClass('validation-passed');
						jQuery(this).parent().find('.validation-advice').remove();
						jQuery(this).after("<div class='validation-advice'>Please enter a valid email address. For example johndoe@domain.com.</div>");
					}
				}else{
					jQuery(this).removeClass('validation-failed');
					jQuery(this).addClass('validation-passed');
					jQuery(this).parent().find('.validation-advice').remove();
				}
			}
		});

		function validateEmail(email) {
			var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
			return re.test(email);
		}
	</script>