<?php $registry = Mage::registry('loaded_registry'); ?>
<?php if ($registry): ?>
    <h3><?php echo $registry->getEventName(); ?></h3>
    <p><strong><?php $this->__('Event Date:') ?> <?php echo $registry->getEventDate(); ?></strong></p>
    <p><strong><?php $this->__('Event Location:') ?> <?php echo $registry->getEventLocation(); ?></strong></p>

    <!--- Add to registry Block START -->
    <?php echo $this->getChildHtml('registry_listitem') ?>
    <!--- Add to registry Block END -->
<?php else: ?>
    No load registry
<?php endif; ?>